WebAppVentas202301/Controllers/ProveedorController.cs
using Microsoft.AspNetCore.Mvc;
using WebAppVentas202301.Models;
using WebAppVentas202301.Services.Interface;

namespace WebAppVentas202301.Controllers
{
    public class ProveedorController : Controller
    {
        private readonly IProveedores objProveedor;
        public ProveedorController(IProveedores objProveedor)
        {
            this.objProveedor = objProveedor;
        }

        public IActionResult Index()
        {
            ViewBag.ListaDeProveedores = objProveedor.GetAllProveedores();
            return View();
        }
        public IActionResult Grabar()
        {
            return View();
        }
    }
}

WebAppVentas202301/Views/Proveedor/Grabar.cshtml
@model IEnumerable<WebAppVentas202301.Models.TbProveedor>


<html>
    <body>
        <h1>LISTADO DE TRANSACCIONES DE PROVEEDORES</h1>
        <h2>
            Buscar<input class="form-control" id="myInput" type="text" placeholder="Search..." />
            <br />
        </h2>
        <table class="table table-hover">
            <thead>
                <tr>
                    <td scope="col">Codigo</td>
                    <td scope="col">Razon Social</td>
                    <td scope="col">Direccion</td>
                    <td scope="col">Telefono</td>
                    <td scope="col">Cod2</td>
                    <td scope="col">Nombre</td>
                    <td scope="col">Editar</td>
                    <td scope="col">Eliminar</td>
            </tr>
            </thead>
            <tbody id="myTable">
                @foreach(var item in Model)
                {
                    <tr>
                    <td>@item.CodPrv</td>
                    <td>@item.RazSocPrv</td>
                    <td>@item.DirPrv</td>
                    <td>@item.TelPrv</td>
                    <td>@item.CodDis</td>
                    <td>@item.RepVen</td>
                        <td><a asp-action="Edit" asp-route-id="@item.CodPrv">Editar</a></td>
                        <td><a asp-action="Delete" asp-route-id="@item.CodPrv">Eliminar</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </body>
</html>
<script>
    $(document).ready(function () {
        $("#myInput").on("keyup", function () {
            var value = $(this).val().toLowerCase();
            $("#myTable tr").filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>

WebAppVentas202301/Views/Proveedor/Index.cshtml
@model WebAppVentas202301.Models.TbProveedor
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<html>
<body>
    <h1> SELECCIONES A SU PROVEEDOR!!! </h1>
    <form asp-controller="Proveedor" asp-action="Grabar" method="post">
        
        <div class="form-group">
            <label for="formGroupExampleInput2">PROVEEDOR</label>
            <!--   <input asp-for="CodDis" class="form-control" id="formGroupExampleInput2" placeholder="DISTRITO">-->
            <select class="form-control" id="formGroupExampleInput2" asp-for="CodPrv" asp-items='@(new SelectList(ViewBag.ListaDeProveedores,"CodPrv","RepVen"))'></select>
            <span asp-validation-for="CodPrv" class="text-danger"></span>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary" value="btn" name="grabar" data-toggle="modal" data-target="#exampleModal">Grabar</button>
        </div>

    </form>


</body>
</html>