WebAppVentas202301/Controllers/ProductoController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WebAppVentas202301.Models;
using WebAppVentas202301.Services.Interface;

namespace WebAppVentas202301.Controllers
{
    public class ProductoController : Controller
    {
        private readonly IProducto objProducto;
        public ProductoController(IProducto objProducto)
        {
            this.objProducto = objProducto;
        }

        public IActionResult Index()
        {
            //Obtener el valor de la variable de sesión 
            var objSesion = HttpContext.Session.GetString("sesionUsuario");
            if (objSesion != null)
            {
                //Deserializar el obj con los datos de la sesión 
                var ObjJeje = JsonConvert.DeserializeObject<Usuario>
                    (HttpContext.Session.GetString("sesionUsuario")); //el objeto de usuario
                return View(objProducto.GetAllProducts());
            }
            else
            {
                return RedirectToAction("Index", "Usuario");
            }
           
        }
        [Route("Producto/Comprar/{cod}")]
        public IActionResult Comprar(string cod)
        {
            ViewData["codigo"] = objProducto.getProducto(cod).CodPro;
            ViewData["descripcion"] = objProducto.getProducto(cod).DesPro;
            ViewData["precio"] = objProducto.getProducto(cod).PrePro;
            ViewData["stock"] = objProducto.getProducto(cod).StkAct;


            return View();
        }
    }
}

WebAppVentas202301/Controllers/TemporalVentaController.cs
using Microsoft.AspNetCore.Mvc;
using WebAppVentas202301.Models;
using WebAppVentas202301.Services.Interface;

namespace WebAppVentas202301.Controllers
{
    public class TemporalVentaController : Controller
    {
        private readonly ITemporalVenta _temporalVenta;
        public TemporalVentaController (ITemporalVenta temporal)
        {
            _temporalVenta = temporal;
        }
        public IActionResult Index(TemporalVenta temporal)
        {
            _temporalVenta.add(temporal);

            return RedirectToAction("Index", "Producto");
        }
        public IActionResult VerCarrito()
        {
            return View(_temporalVenta.GetAllTemporarySale());
        }
    }
}

WebAppVentas202301/Views/Producto/Comprar.cshtml
@model WebAppVentas202301.Models.TemporalVenta
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<html>
<head>

</head>
<body>
    <form asp-controller="TemporalVenta" asp-action="Index" method="post">
        <input asp-for="CodPro" type="hidden" class="form-control" value="@ViewData["codigo"]"/>
        <label for="formGroupExampleInput">Descripcion</label>
        <input asp-for="DesPro" type="text" class="form-control" placeholder="Descripcion del producto" value="@ViewData["descripcion"]"/>
        <label for="formGroupExampleInput">Precio</label>
        <input asp-for="PrePro" type="text" class="form-control" placeholder="Precio del producto" value="@ViewData["precio"]" />
        <label for="formGroupExampleInput">Stock</label>
        <input asp-for="StkPro" type="number" class="form-control" placeholder="Precio del producto" value="@ViewData["stock"]" />
        <label for="formGroupExampleInput">Cantidad</label>
        <input asp-for="cantidad" type="number" class="form-control" placeholder="Cantidad de productos" />
        <input type="submit" class="btn btn-primary" value="Agregar al carrito" />
    </form>
</body>
</html>

WebAppVentas202301/Views/Producto/Index.cshtml
@model IEnumerable<WebAppVentas202301.Models.TbProducto>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<html>
    <body>
        <div class="card-deck">
            @foreach(var item in Model)
            {
                <div class="card m-4" style="min-width:auto;max-width:30.5%">
                    <div class="card-header">
                        <h3>@item.DesPro</h3>
                        <h3>@item.PrePro</h3>
                        <h3>@item.StkAct</h3>
                    </div>
                    <div class="card-footer text-center">
                        <a asp-action="Comprar" asp-route-id="@item.CodPro" class="btn btn-primary m-2">Comprar</a>
                    </div>
                </div>
            }
        </div>
    </body>
</html>